---
- name: Include tasks defined variables.
  include_tasks: "defined/main.yml"

- name: Add user
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.append }}"
    append: yes
  loop: "{{ user_names }}"
  tags:
    - adduser

- name: Set authorized public key
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', '{{ path_files_directory }}/{{ item.name }}/{{ item.name }}.key.pub') }}"
  loop: "{{ user_names }}"
  when: item.auth_key
  tags:
    - authorized_key

- name: add user to sudo
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ (item.name) | replace('.','') }}"
    content: |
      {{ item.name  }}    ALL=(ALL)       NOPASSWD: ALL
  loop: "{{ user_names }}"
  when: item.sudo
  tags:
    - addsudo

- name: copy private key
  ansible.builtin.copy:
    src: "{{ path_files_directory }}/{{ item.name }}/{{ item.name }}.key' }}"
    dest: "/home/{{ item.name }}/.ssh/id_rsa.git"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0400'
  loop: "{{ user_names }}"
  when: item.git
  tags:
    - private_key

- name: add ssh config
  ansible.builtin.copy:
    dest: "/home/{{ item.name }}/.ssh/config"
    content: |
       Host github.com
       HostName github.com
       IdentityFile ~/.ssh/id_rsa.git
       IdentitiesOnly yes
       User git
  when: item.git
