---
- name: Include tasks defined variables.
  include_tasks: "defined/main.yml"

- name: Add user
  ansible.builtin.user:
    name: "{{ item.user }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.append }}"
    append: yes
  loop: "{{ ssh_users }}"
  tags:
    - adduser

- name: Set authorized public key
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    state: present
    key: "{{ lookup('file', '{{ ssh_directory_users_keys }}/{{ item.user }}/{{ item.user }}.pub') }}"
  loop: "{{ ssh_users }}"
  when: item.auth_key
  tags:
    - authorized_key

- name: add user to sudo
  community.general.sudoers:
    name: "{{ item.user | replace('.','') }}"
    state: present
    user: "{{ item.user }}"
    commands: ALL
    nopassword: true
  when: item.sudo
  loop: "{{ ssh_users }}"

- name: copy private key
  ansible.builtin.copy:
    src: "{{ ssh_directory_users_keys }}/{{ item.user }}/{{ item.user }}"
    dest: "{{ item.path_key_pair }}/id_rsa"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: '0400'
  loop: "{{ ssh_users }}"
  when: item.path_key_pair is defined
  tags:
    - pair_key

- name: copy public key
  ansible.builtin.copy:
    src: "{{ ssh_directory_users_keys }}/{{ item.user }}/{{ item.user }}.pub"
    dest: "{{ item.path_key_pair }}/id_rsa.pub"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: '0400'
  loop: "{{ ssh_users }}"
  when: item.path_key_pair is defined
  tags:
    - pair_key

- name: copy private key
  ansible.builtin.copy:
    src: "{{ ssh_directory_users_keys }}/{{ item.user }}/{{ item.user }}"
    dest: "/home/{{ item.user }}/.ssh/id_rsa.git"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: '0400'
  loop: "{{ ssh_users }}"
  when: item.git
  tags:
    - private_key

- name: add ssh config
  ansible.builtin.copy:
    dest: "/home/{{ item.user }}/.ssh/config"
    content: |
       Host github.com
       HostName github.com
       IdentityFile ~/.ssh/id_rsa.git
       IdentitiesOnly yes
       User git
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: '0400'
  loop: "{{ ssh_users }}"
  when: item.git
