---
- name: Include tasks defined variables.
  ansible.builtin.include_tasks: "defined/main.yml"

- name: Include tasks user management
  ansible.builtin.include_tasks: "./user_management.yml"
  loop: "{{ ssh_users }}"
  loop_control:
    label: "{{ item.user }}"
