---
- name: Define path_files_directory.
  set_fact:
    path_files_directory: "{{ __path_files_directory }}"
  when: path_files_directory is not defined

- name: Define ssh_users.
  set_fact:
    ssh_users: "{{ user_users | default(__ssh_users) }}"
  when: ssh_users is not defined
