---
- name: Define ssh_directory_users_keys.
  set_fact:
    ssh_directory_users_keys: "{{ __ssh_directory_users_keys }}"
  when: ssh_directory_users_keys is not defined

- name: Define ssh_users.
  set_fact:
    ssh_users: "{{ user_names | default(__ssh_users) }}"
  when: ssh_users is not defined
